---
title: "Analyzing script tags"
---

```{r echo=FALSE, message=FALSE, error=FALSE, warning=FALSE}
library(tidyverse)
library(DBI)
library(RPostgres)
library(urltools)
library(googlesheets4)


source("../config/config-secret.R")
source("../config/config-graphic.R")
source("../config/config.R")

# gs4_auth(cache=".secrets")
# gs_domain_to_look <- read_sheet(SPREADSHEET_PATH_GENERELL, sheet = SPREADSHEET_PATH_DOMAINS[[{{CURRENT_SPHERE}}]]) %>% 
#   select(Name, URL) %>% 
#   mutate(site = domain(URL) %>% suffix_extract(.) %>% select(domain) %>% pull(.)) 
# 

con <- dbConnect(RPostgres::Postgres(),
                 dbname = dsn_database,
                 host = dsn_hostname,
                 port = dsn_port,
                 user = dsn_uid,
                 password = dsn_pwd
)

# dbDisconnect(con)

get_script_tags <- function(sphere){
  df <- dbGetQuery(conn = con, paste0("SELECT s.crawl_date, s.site, s.sha1, t.tag, t.name, t.attr, t.group FROM sites s INNER JOIN tags_2 t ON t.site = s.sha1 WHERE s.sphere = '", sphere, "' AND t.tag = 'script' ORDER BY s.crawl_date"))
}

# 7a7680601a641ca3f1ad02053e6aa35fe53c111e

# test <- dbGetQuery(conn = con, paste0("SELECT DISTINCT s.crawl_date, s.sphere, s.site, s.url, s.sha1, tc.parent_path_str, tc.group, tc.name, tc.attr, tc.value, tc.text FROM sites s INNER JOIN tags_context tc ON tc.site = s.sha1 WHERE s.sphere LIKE 'German' AND tc.site LIKE '7a7680601a641ca3f1ad02053e6aa35fe53c111e'  ORDER BY s.sha1, tc.group"))
# # 
# test2 <- dbGetQuery(conn = con, paste0("SELECT DISTINCT s.crawl_date, s.sphere, s.site, s.url, s.sha1, tc.parent_path_str, tc.group, tc.name, tc.attr, tc.value, tc.text FROM sites s INNER JOIN tags_context tc ON tc.site = s.sha1 WHERE s.sphere LIKE 'German' AND tc.site LIKE 'cc879db7bc2bf85ace60968cfcb31be123592d13'  ORDER BY s.sha1, tc.group"))


```

```{r}

# scripts_embedded <- read_csv("../../data/1-parsing/scripts/German/scripts-raw-2th-delivery-groups-test.csv")
# 
# scripts_called <- get_script_tags("German")

```

wenn alles geparsed ist: 
  - beide dateien zusammenführen - done
  - distincten - done
  - Datenbanktabelle erweitern um content-spalte - done
  - aktuelle Tabelle abrufen mit tags-id - done
  - joinen mit tatsächlichem content - done
  - filtern auf !is.na(content) - done
  - update table fahren
  



